theme: minima
title: Coding Projects 2025 - 2026
author: Averi Wylie
description: This website contains all projects created by Averi Wylie in the 2025, and 2026 years. Any project done in partnership with another programmer will express as such.
base: main
compare: my-pages
